"""Domain models and errors for the standalone chat project."""

from engllm_chat.domain.errors import (
    AnalysisError,
    ConfigError,
    EngLLMError,
    GitError,
    LLMError,
    RenderingError,
    RepositoryError,
    ValidationError,
)
from engllm_chat.domain.models import (
    ChatAssistantCompletionState,
    ChatCitation,
    ChatConfig,
    ChatCredentialPromptMetadata,
    ChatFinalResponse,
    ChatLLMConfig,
    ChatMessage,
    ChatMessageRole,
    ChatProvider,
    ChatSessionConfig,
    ChatSourceFilters,
    ChatTokenUsage,
    ChatToolCall,
    ChatToolLimits,
    ChatToolResult,
    ChatUIConfig,
    DomainModel,
    QueryAnswer,
    SectionDraft,
    SectionUpdateProposal,
)

__all__ = [
    "AnalysisError",
    "ChatAssistantCompletionState",
    "ChatCitation",
    "ChatConfig",
    "ChatCredentialPromptMetadata",
    "ChatFinalResponse",
    "ChatLLMConfig",
    "ChatMessage",
    "ChatMessageRole",
    "ChatProvider",
    "ChatSessionConfig",
    "ChatSourceFilters",
    "ChatTokenUsage",
    "ChatToolCall",
    "ChatToolLimits",
    "ChatToolResult",
    "ChatUIConfig",
    "ConfigError",
    "DomainModel",
    "EngLLMError",
    "GitError",
    "LLMError",
    "QueryAnswer",
    "RenderingError",
    "RepositoryError",
    "SectionDraft",
    "SectionUpdateProposal",
    "ValidationError",
]
