"""Deterministic mock LLM provider."""

from __future__ import annotations

import re
from typing import Any

from pydantic import BaseModel

from engllm_chat.domain.models import (
    ChatFinalResponse,
    ChatMessage,
    QueryAnswer,
    SectionDraft,
    SectionUpdateProposal,
)
from engllm_chat.llm.base import (
    ChatTurnRequest,
    ChatTurnResponse,
    StructuredGenerationRequest,
    StructuredGenerationResponse,
    validate_payload,
)


class MockLLMClient:
    """Mock implementation that returns deterministic structured data."""

    def __init__(
        self,
        model_name: str = "mock-engllm",
        canned: dict[str, dict[str, Any]] | None = None,
        chat_canned_turns: list[ChatTurnResponse] | None = None,
    ) -> None:
        self.model_name = model_name
        self.canned = canned or {}
        self._chat_canned_turns = list(chat_canned_turns or [])
        self._chat_turn_index = 0

    def _extract_section_info(self, prompt: str) -> tuple[str, str]:
        section_id_match = re.search(r'"id"\s*:\s*"([^"]+)"', prompt)
        title_match = re.search(r'"title"\s*:\s*"([^"]+)"', prompt)
        section_id = section_id_match.group(1) if section_id_match else "TBD"
        title = title_match.group(1) if title_match else "TBD"
        return section_id, title

    def _build_payload(self, request: StructuredGenerationRequest) -> dict[str, Any]:
        model_name = request.response_model.__name__
        if model_name in self.canned:
            return self.canned[model_name]

        if request.response_model is SectionDraft:
            section_id, title = self._extract_section_info(request.user_prompt)
            return {
                "section_id": section_id,
                "title": title,
                "content": f"TBD: Draft content for section {section_id} ({title}).",
                "evidence_refs": [],
                "assumptions": [
                    "Generated by mock provider using supplied evidence only."
                ],
                "missing_information": ["TBD"],
                "confidence": 0.55,
            }

        if request.response_model is SectionUpdateProposal:
            section_id, title = self._extract_section_info(request.user_prompt)
            return {
                "section_id": section_id,
                "title": title,
                "existing_text": "TBD",
                "proposed_text": (
                    f"TBD: Proposed update for section {section_id} ({title})."
                ),
                "rationale": (
                    "Commit impact indicates this section may require revision."
                ),
                "uncertainty_list": ["TBD"],
                "review_priority": "medium",
                "evidence_refs": [],
            }

        if request.response_model in {QueryAnswer, ChatFinalResponse}:
            return {
                "answer": "TBD: Evidence is available but this is a mock answer.",
                "citations": [],
                "uncertainty": ["Mock provider used."],
                "missing_information": ["TBD"],
                "confidence": 0.45,
            }

        return self._default_payload(request.response_model)

    def _default_payload(self, response_model: type[BaseModel]) -> dict[str, Any]:
        payload: dict[str, Any] = {}
        for name, field in response_model.model_fields.items():
            annotation = field.annotation
            origin_name = getattr(annotation, "__name__", "")
            if annotation is str:
                payload[name] = "TBD"
            elif annotation in (int, float):
                payload[name] = 0
            elif annotation is bool:
                payload[name] = False
            elif origin_name == "list":
                payload[name] = []
            elif origin_name == "dict":
                payload[name] = {}
            else:
                payload[name] = None
        return payload

    def generate_structured(
        self,
        request: StructuredGenerationRequest,
    ) -> StructuredGenerationResponse:
        """Return deterministic schema-valid content without network calls."""

        payload = self._build_payload(request)
        parsed = validate_payload(request.response_model, payload)
        return StructuredGenerationResponse(
            content=parsed,
            raw_text=parsed.model_dump_json(),
            model_name=self.model_name,
        )

    def generate_chat_turn(self, request: ChatTurnRequest) -> ChatTurnResponse:
        """Return deterministic non-streaming chat turns without network calls."""

        if self._chat_turn_index < len(self._chat_canned_turns):
            turn = self._chat_canned_turns[self._chat_turn_index]
            self._chat_turn_index += 1
            return turn

        payload = self._build_payload(
            StructuredGenerationRequest(
                system_prompt="",
                user_prompt="",
                response_model=request.response_model,
                model_name=request.model_name,
                temperature=request.temperature,
            )
        )
        parsed = validate_payload(request.response_model, payload)
        raw_text = parsed.model_dump_json()
        return ChatTurnResponse(
            assistant_message=ChatMessage(role="assistant", content=raw_text),
            final_response=parsed,
            token_usage=None,
            raw_text=raw_text,
            finish_reason="final_response",
        )
